"use server";

import { revalidatePath } from "next/cache";
import { requireRoleClient } from "@/lib/auth/session";
import type { DbClient } from "@/lib/supabase/types";
import { appTimeToDate } from "@/lib/utils/datetime";
import { parseUuid } from "@/lib/validations/common";
import {
  CREDENTIAL_FILE_TYPES,
  hasValidFileSignature,
  parseApplicationForm,
  type ApplicationInput,
} from "@/lib/validations/application";
import { availabilitySchema, profileSchema } from "@/lib/validations/tutor";

export type TutorFormState = {
  error?: string;
  success?: string;
  /** One message per invalid field, keyed by the field's name. */
  fieldErrors?: Record<string, string>;
} | null;

/* ---------------------------------------------------------------------------
 * Tutor application
 * ------------------------------------------------------------------------- */

/** A tutor has at most one application, so it is found by the signed-in user — never by an id from the form. */
async function findApplication(supabase: DbClient, tutorId: string) {
  const { data } = await supabase
    .from("tutor_applications")
    .select("id, tutor_credentials(id)")
    .eq("tutor_id", tutorId)
    .maybeSingle();
  return data ? { id: data.id, hasCredential: data.tutor_credentials.length > 0 } : null;
}

/** Updates the existing application, or creates it as a draft. */
async function saveApplicationRow(
  supabase: DbClient,
  tutorId: string,
  existingId: string | null,
  data: ApplicationInput,
): Promise<{ id: string } | { error: string }> {
  const row = {
    school_name: data.schoolName,
    degree: data.degree,
    major: data.major,
    graduation_year: data.graduationYear,
    academic_achievements: data.academicAchievements ?? null,
    teaching_experience_summary: data.experience,
    years_experience: data.yearsExperience,
    teaching_approach: data.teachingApproach,
    preferred_modes: data.preferredModes,
  };

  if (existingId) {
    const { error } = await supabase
      .from("tutor_applications")
      .update(row)
      .eq("id", existingId)
      .eq("tutor_id", tutorId);
    if (error) return { error: "Unable to save your application. Please check the details and try again." };
    return { id: existingId };
  }

  const { data: created, error } = await supabase
    .from("tutor_applications")
    .insert({ ...row, tutor_id: tutorId, status: "draft" })
    .select("id")
    .single();
  if (error || !created) return { error: "Unable to submit your application. Please try again." };
  return { id: created.id };
}

/** Replaces the subject selection for an application. Returns an error message or null. */
async function replaceApplicationSubjects(
  supabase: DbClient,
  applicationId: string,
  subjectIds: string[],
): Promise<string | null> {
  await supabase.from("tutor_application_subjects").delete().eq("application_id", applicationId);

  const { error } = await supabase
    .from("tutor_application_subjects")
    .insert(subjectIds.map((subject_id) => ({ application_id: applicationId, subject_id })));
  return error ? "Application saved, but subjects could not be saved." : null;
}

/** A display-safe copy of the uploaded file name (no paths, no control characters). */
function cleanFileName(name: string): string {
  return name.replace(/[\\/]/g, "_").replace(/[^\x20-\x7E]/g, "").trim().slice(0, 150) || "document";
}

/** Uploads a credential file and records its metadata. Returns an error message or null. */
async function saveCredential(
  supabase: DbClient,
  tutorId: string,
  applicationId: string,
  credentialType: ApplicationInput["credentialType"],
  file: File,
): Promise<string | null> {
  // Type and size were checked by parseApplicationForm; this checks the file's real content.
  if (!(await hasValidFileSignature(file))) return "That file does not look like a real PDF, JPG, or PNG.";

  // The stored name is generated by us; the user's file name never becomes part of the path.
  const storagePath = `${tutorId}/${applicationId}/${crypto.randomUUID()}.${CREDENTIAL_FILE_TYPES[file.type]}`;

  const { error: uploadError } = await supabase.storage
    .from("tutor-credentials")
    .upload(storagePath, file, { contentType: file.type, upsert: false });
  if (uploadError) return "Application saved, but the credential upload failed.";

  const { error: recordError } = await supabase.from("tutor_credentials").insert({
    application_id: applicationId,
    credential_type: credentialType,
    storage_path: storagePath,
    file_name: cleanFileName(file.name),
    mime_type: file.type,
    file_size: file.size,
  });
  return recordError ? "Application saved, but the credential record failed." : null;
}

/** Marks a saved application as pending admin review. Returns an error message or null. */
async function submitForReview(
  supabase: DbClient,
  applicationId: string,
  tutorId: string,
): Promise<string | null> {
  const { error } = await supabase
    .from("tutor_applications")
    .update({ status: "pending" })
    .eq("id", applicationId)
    .eq("tutor_id", tutorId);
  return error ? "Your application was saved, but could not be submitted for review." : null;
}

export async function saveTutorApplication(
  _previous: TutorFormState,
  formData: FormData,
): Promise<TutorFormState> {
  const { profile, supabase } = await requireRoleClient("tutor");

  const existing = await findApplication(supabase, profile.id);
  const parsed = parseApplicationForm(formData, { hasCredential: existing?.hasCredential ?? false });
  if ("errors" in parsed) return { fieldErrors: parsed.errors };

  const { data, file } = parsed;
  const saved = await saveApplicationRow(supabase, profile.id, existing?.id ?? null, data);
  if ("error" in saved) return { error: saved.error };

  const subjectsError = await replaceApplicationSubjects(supabase, saved.id, data.subjectIds);
  if (subjectsError) return { error: subjectsError };

  if (file) {
    const credentialError = await saveCredential(supabase, profile.id, saved.id, data.credentialType, file);
    if (credentialError) return { error: credentialError };
  }

  const submitError = await submitForReview(supabase, saved.id, profile.id);
  if (submitError) return { error: submitError };

  revalidatePath("/tutor/dashboard");
  return { success: "Your application was submitted for admin review." };
}

/* ---------------------------------------------------------------------------
 * Availability
 * ------------------------------------------------------------------------- */

async function getTutorProfileId(supabase: DbClient, profileId: string): Promise<string | null> {
  const { data } = await supabase
    .from("tutor_profiles")
    .select("id")
    .eq("profile_id", profileId)
    .maybeSingle();
  return data?.id ?? null;
}

export async function createAvailability(
  _previous: TutorFormState,
  formData: FormData,
): Promise<TutorFormState> {
  const { profile, supabase } = await requireRoleClient("tutor");

  const tutorProfileId = await getTutorProfileId(supabase, profile.id);
  if (!tutorProfileId) return { error: "Your tutor profile is not ready yet." };

  const parsed = availabilitySchema.safeParse({
    dayDate: formData.get("dayDate"),
    startTime: formData.get("startTime"),
    endTime: formData.get("endTime"),
    duration: formData.get("duration"),
    subjectId: formData.get("subjectId"),
  });
  if (!parsed.success) return { error: parsed.error.issues[0].message };

  const { dayDate, startTime, endTime, duration, subjectId } = parsed.data;
  if (appTimeToDate(dayDate, startTime) <= new Date()) {
    return { error: "Choose a future date and time." };
  }

  const { error } = await supabase.from("availability").insert({
    tutor_profile_id: tutorProfileId,
    subject_id: subjectId ?? null,
    day_date: dayDate,
    start_time: startTime,
    end_time: endTime,
    slot_duration_minutes: duration,
  });
  if (error) {
    return { error: "Unable to create availability. Check that the time window does not overlap another one." };
  }

  revalidatePath("/tutor/dashboard");
  return { success: "Availability added and appointment slots generated." };
}

export async function deleteAvailability(formData: FormData) {
  const { profile, supabase } = await requireRoleClient("tutor");

  const availabilityId = parseUuid(formData, "availabilityId");
  const tutorProfileId = await getTutorProfileId(supabase, profile.id);
  if (!availabilityId || !tutorProfileId) return;

  await supabase
    .from("availability")
    .delete()
    .eq("id", availabilityId)
    .eq("tutor_profile_id", tutorProfileId);

  revalidatePath("/tutor/dashboard");
}

/* ---------------------------------------------------------------------------
 * Public profile
 * ------------------------------------------------------------------------- */

export async function updateTutorProfile(
  _previous: TutorFormState,
  formData: FormData,
): Promise<TutorFormState> {
  const { profile, supabase } = await requireRoleClient("tutor");

  const parsed = profileSchema.safeParse({
    headline: formData.get("headline"),
    bio: formData.get("bio"),
  });
  if (!parsed.success) return { error: "Headline must be 150 characters or fewer and bio 2000 or fewer." };

  const { error } = await supabase
    .from("tutor_profiles")
    .update({ headline: parsed.data.headline ?? null, bio: parsed.data.bio ?? null })
    .eq("profile_id", profile.id);
  if (error) return { error: "Unable to update your public profile." };

  revalidatePath("/tutor/dashboard");
  revalidatePath("/tutors");
  return { success: "Your public profile was updated." };
}
